### ISSUE TITLE
process to correct BALANCE 

### ISSUE THREAD

**Issue by jalazawa** [rte-antares-rpackage/antaresProcessing#33]
process will be something like that 

```R 

BALANCE := BALANCE + ROW BALANCE 

```

correct_balance to add ?

**Comment by nabonswende** [comment]
SLT!
C'est plutôt 
BALANCE := BALANCE - ROW BALANCE 
Pour un Area donné, les échanges avec le ROW, c'est : >0 pour import du area, <0 pour l'export.

**Comment by jalazawa** [comment]
Should we remove ROW. BALANCE after the correction ? or but 0 on this column? If we keep this column we can sometimes count twice ROW. BAL.

**Comment by jalazawa** [comment]
Done
